export const btnArr = [
  {text: 'C', textColor: true, containerColor: 'grayLight', double: false},
  {text: '%', textColor: true, containerColor: 'grayLight', double: false},
  {text: '%', textColor: true, containerColor: 'grayLight', double: false},
  {text: '/', textColor: false, containerColor: 'orange', double: false},
  {text: '7', textColor: false, containerColor: 'gray', double: false},
  {text: '8', textColor: false, containerColor: 'gray', double: false},
  {text: '9', textColor: false, containerColor: 'gray', double: false},
  {text: 'X', textColor: false, containerColor: 'orange', double: false},
  {text: '4', textColor: false, containerColor: 'gray', double: false},
  {text: '5', textColor: false, containerColor: 'gray', double: false},
  {text: '6', textColor: false, containerColor: 'gray', double: false},
  {text: '-', textColor: false, containerColor: 'orange', double: false},
  {text: '1', textColor: false, containerColor: 'gray', double: false},
  {text: '2', textColor: false, containerColor: 'gray', double: false},
  {text: '3', textColor: false, containerColor: 'gray', double: false},
  {text: '+', textColor: false, containerColor: 'orange', double: false},
  {text: '0', textColor: false, containerColor: 'gray', double: true},
  {text: ',', textColor: false, containerColor: 'gray', double: false},
  {text: '=', textColor: false, containerColor: 'orange', double: false},
];
